services:
  - mysql
sudo: false
cache: bundler
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.3.1
env:
  - RAILS_VERSION=3
  - RAILS_VERSION=4
  - RAILS_VERSION=5
matrix:
  exclude:
  - rvm: 2.0.0
    env: RAILS_VERSION=5
  - rvm: 2.1.0
    env: RAILS_VERSION=5
  - rvm: 2.2.0
    env: RAILS_VERSION=5
before_install: gem install bundler -v 1.12.5
before_script:
  - cp config/database.travis.yml config/database.yml
  - bin/setup
script: bundle exec rspec
